"""WP-10 -- Stress-Kanon: STRESS_REL (DEC-55) und STRESS_ABS (DEC-56).

Deterministic day-lists computed from the WP-0 bar cache's realized vol
(``rv.daily_realized_vol``, ONE shared definition -- see that module's
docstring). Both are fixtures, pinned with SHA-256, generated by this
module and NEVER by hand.

**STRESS_REL (DEC-55)** -- a Abdeckungs-Nachweis, NEVER a filter/gate: a
day is flagged when its realized vol (BTC OR ETH) exceeds the
``STRESS_REL_PCTL`` percentile of a TRAILING ``STRESS_REL_WINDOW_DAYS``
window ending on that day (a genuine ROLLING percentile -- DEC-56's whole
point is that a rolling cut produces ~constant coverage in every window
by construction, which is exactly why it can never carry a gate
threshold). Plus the named reference day.

**STRESS_ABS (DEC-56)** -- the Stress-Definition WP-10(A) actually uses: a
day is flagged when its realized vol (BTC OR ETH) exceeds the
``STRESS_ABS_PCTL`` percentile of the ENTIRE available WP-0 history (one
GLOBAL threshold per symbol, not rolling), plus the two named reference
days. 99%, the two named days, 97.5%, 24 months and the gap rule are
DESIGN PARAMETERS (spec: "kein Gate, nicht variierbar") -- never adjusted
per-hypothesis.

Both canons group consecutive flagged days (allowing up to
``gap_max_days`` non-stress days between them) into ONE episode
(DEC-55's "Luecken-Regel", applied identically to STRESS_ABS for the
"Episodenzahl" effective-N WP-10(A) needs).

**Append-only (DEC-55: "wird ... fortgeschrieben; alte Eintraege aendern
sich nicht")**: ``merge_append_only`` UNIONS a freshly (re)computed
fixture's day-set with a previously written one -- a day's flagged
membership, once written, is PERMANENT, so the merge itself can never
"drop" an old day (union is monotone by construction; recomputing a
percentile threshold over a larger, newer history routinely disagrees
with old borderline days near the cut, and that disagreement must never
retroactively un-flag them). What DOES raise
``AppendOnlyViolationError`` is a genuine violation of the pinned
DESIGN PARAMETERS themselves (spec: "kein Gate, nicht variierbar") --
``canon``, ``pctl``, ``gap_max_days`` and (STRESS_REL only)
``window_days`` must be IDENTICAL between the old file and a fresh
write; a hypothesis is never allowed to quietly redefine the canon it
reads. Episode SHAPE may legitimately change as new adjacent days fill
gaps (that's a grouping artefact, not a membership change).

KAPITALFREI: pure measurement/fixture generation. No cost quantity.
"""
from __future__ import annotations

import bisect
import hashlib
import json
from datetime import date
from pathlib import Path
from typing import Any

import numpy as np

from bybit_edge.research.bar_cache import load_minute_bars

from . import rv as _rv

__all__ = [
    "StressCanonError", "AppendOnlyViolationError",
    "STRESS_REL_PCTL", "STRESS_REL_WINDOW_DAYS", "STRESS_REL_GAP_MAX_DAYS",
    "STRESS_REL_NAMED_DATES",
    "STRESS_ABS_PCTL", "STRESS_ABS_GAP_MAX_DAYS", "STRESS_ABS_NAMED_DATES",
    "rv_panel", "group_episodes", "build_stress_abs", "build_stress_rel",
    "fixture_sha256", "finalize_fixture", "merge_append_only",
    "write_fixture", "read_fixture",
]

#: DEC-55 design parameters.
STRESS_REL_PCTL = 97.5
#: "juengste 24 Monate" -- repo convention for 24 months (c11_anen UNLOCK
#: gate already uses 730 Tage for the same span).
STRESS_REL_WINDOW_DAYS = 730
STRESS_REL_GAP_MAX_DAYS = 1
STRESS_REL_NAMED_DATES: tuple[str, ...] = ("2026-08-19",)

#: DEC-56 design parameters.
STRESS_ABS_PCTL = 99.0
STRESS_ABS_GAP_MAX_DAYS = 1
STRESS_ABS_NAMED_DATES: tuple[str, ...] = ("2025-10-10", "2026-08-19")


class StressCanonError(RuntimeError):
    """Loud failure: the stress canon cannot be computed from the given input."""


class AppendOnlyViolationError(StressCanonError):
    """DEC-55 append-only violation: a previously flagged day was dropped."""


def rv_panel(cache_dir: Path | str, exchange: str, symbols: list[str],
            start: str, end: str) -> dict[str, dict[str, float]]:
    """``{symbol: {day: rv}}`` -- non-annualized RV, one query per symbol."""
    return {s: _rv.daily_realized_vol(load_minute_bars(cache_dir, exchange, s, start, end))
            for s in symbols}


def group_episodes(days_sorted: list[str], gap_max_days: int) -> list[list[str]]:
    """Consecutive flagged days, allowing up to ``gap_max_days`` calendar
    days of gap between them, grouped into ONE episode each."""
    if not days_sorted:
        return []
    ordinals = [date.fromisoformat(d).toordinal() for d in days_sorted]
    episodes: list[list[str]] = [[days_sorted[0]]]
    for i in range(1, len(days_sorted)):
        gap = ordinals[i] - ordinals[i - 1] - 1
        if gap <= gap_max_days:
            episodes[-1].append(days_sorted[i])
        else:
            episodes.append([days_sorted[i]])
    return episodes


def _global_pctl_flags(rv_by_day: dict[str, float], pctl: float) -> tuple[set[str], float]:
    if not rv_by_day:
        return set(), float("nan")
    vals = np.asarray(list(rv_by_day.values()), dtype=np.float64)
    thr = float(np.percentile(vals, pctl))
    return {d for d, v in rv_by_day.items() if v > thr}, thr


def _rolling_pctl_flags(rv_by_day: dict[str, float], *, pctl: float, window_days: int) -> set[str]:
    """TRUE rolling percentile: threshold at day d = pctl of values in the
    trailing ``[d - window_days, d]`` window (inclusive of d itself --
    DEC-56's ~constant-coverage-per-window property needs the CURRENT day
    counted in its own reference distribution, else short early windows
    would systematically under-flag)."""
    days_sorted = sorted(rv_by_day)
    if not days_sorted:
        return set()
    ordinals = [date.fromisoformat(d).toordinal() for d in days_sorted]
    values = [rv_by_day[d] for d in days_sorted]
    flagged: set[str] = set()
    for i, d in enumerate(days_sorted):
        lo = ordinals[i] - window_days
        j = bisect.bisect_left(ordinals, lo)
        window_vals = values[j:i + 1]
        if len(window_vals) < 2:
            continue
        thr = float(np.percentile(np.asarray(window_vals, dtype=np.float64), pctl))
        if values[i] > thr:
            flagged.add(d)
    return flagged


def build_stress_abs(panel: dict[str, dict[str, float]], *,
                     pctl: float = STRESS_ABS_PCTL,
                     named_dates: tuple[str, ...] = STRESS_ABS_NAMED_DATES,
                     gap_max_days: int = STRESS_ABS_GAP_MAX_DAYS) -> dict[str, Any]:
    """STRESS_ABS (DEC-56): global per-symbol percentile, union across symbols."""
    flagged: set[str] = set(named_dates)
    thresholds: dict[str, float] = {}
    n_days_used: dict[str, int] = {}
    for sym, series in panel.items():
        days_over, thr = _global_pctl_flags(series, pctl)
        thresholds[sym] = thr
        n_days_used[sym] = len(series)
        flagged |= days_over
    days_sorted = sorted(flagged)
    episodes = group_episodes(days_sorted, gap_max_days)
    return {
        "canon": "STRESS_ABS", "decision": "DEC-56", "pctl": pctl,
        "gap_max_days": gap_max_days, "named_dates": list(named_dates),
        "thresholds": thresholds, "n_days_used_per_symbol": n_days_used,
        "days": days_sorted, "episodes": episodes,
        "n_days": len(days_sorted), "n_episodes": len(episodes),
    }


def build_stress_rel(panel: dict[str, dict[str, float]], *,
                     pctl: float = STRESS_REL_PCTL,
                     window_days: int = STRESS_REL_WINDOW_DAYS,
                     named_dates: tuple[str, ...] = STRESS_REL_NAMED_DATES,
                     gap_max_days: int = STRESS_REL_GAP_MAX_DAYS) -> dict[str, Any]:
    """STRESS_REL (DEC-55): trailing rolling percentile, union across symbols."""
    flagged: set[str] = set(named_dates)
    n_days_used: dict[str, int] = {}
    for sym, series in panel.items():
        n_days_used[sym] = len(series)
        flagged |= _rolling_pctl_flags(series, pctl=pctl, window_days=window_days)
    days_sorted = sorted(flagged)
    episodes = group_episodes(days_sorted, gap_max_days)
    return {
        "canon": "STRESS_REL", "decision": "DEC-55", "pctl": pctl,
        "window_days": window_days, "gap_max_days": gap_max_days,
        "named_dates": list(named_dates), "n_days_used_per_symbol": n_days_used,
        "days": days_sorted, "episodes": episodes,
        "n_days": len(days_sorted), "n_episodes": len(episodes),
    }


def fixture_sha256(fixture: dict[str, Any]) -> str:
    """SHA-256 over the canonical (sorted-key, no-whitespace) JSON encoding
    of ``fixture`` MINUS any pre-existing ``sha256`` key (so re-hashing a
    finalized fixture reproduces the same hash it was finalized with)."""
    payload = {k: v for k, v in fixture.items() if k != "sha256"}
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def finalize_fixture(fixture: dict[str, Any]) -> dict[str, Any]:
    return {**fixture, "sha256": fixture_sha256(fixture)}


#: DEC-55/56 pinned design parameters -- identical between an on-disk
#: fixture and any fresh write, or ``merge_append_only`` refuses (loud).
#: ``window_days`` only applies to STRESS_REL (absent/None for STRESS_ABS).
_PINNED_PARAM_KEYS: tuple[str, ...] = ("canon", "pctl", "gap_max_days", "window_days")


def merge_append_only(old: dict[str, Any], new: dict[str, Any]) -> dict[str, Any]:
    """Union ``old`` (previously written fixture) with a freshly computed
    ``new`` fixture, enforcing append-only.

    Raises ``AppendOnlyViolationError`` if the two disagree on a PINNED
    design parameter (``canon``/``pctl``/``gap_max_days``/``window_days``)
    -- never merely because a fresh recompute disagrees with history on
    some individual day's membership (that disagreement is exactly what
    the union is FOR: old flagged days are always kept). Episodes are
    always RECOMPUTED from the merged day set.
    """
    for key in _PINNED_PARAM_KEYS:
        old_val, new_val = old.get(key), new.get(key)
        if old_val != new_val:
            raise AppendOnlyViolationError(
                f"pinned design parameter {key!r} changed: old={old_val!r} "
                f"new={new_val!r} -- STRESS_ABS/STRESS_REL parameters are "
                f"design constants (DEC-55/56), never variable per-run")
    merged_days = sorted(set(old.get("days", [])) | set(new.get("days", [])))
    gap_max_days = new.get("gap_max_days", STRESS_ABS_GAP_MAX_DAYS)
    episodes = group_episodes(merged_days, gap_max_days)
    return {**new, "days": merged_days, "episodes": episodes,
            "n_days": len(merged_days), "n_episodes": len(episodes)}


def _refuse_harvest(path: Path) -> None:
    if "data/harvest" in str(path).replace("\\", "/"):
        raise ValueError(f"refusing to write stress-canon fixture under data/harvest: {path}")


def write_fixture(fixture: dict[str, Any], path: Path | str, *,
                  merge_with_existing: bool = True) -> dict[str, Any]:
    """Finalize (SHA-256), append-only-merge with an existing file at
    ``path`` if present, and write. NEVER under ``data/harvest``."""
    path = Path(path)
    _refuse_harvest(path)
    if merge_with_existing and path.is_file():
        old = read_fixture(path)
        fixture = merge_append_only(old, fixture)
    finalized = finalize_fixture(fixture)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(finalized, indent=2, sort_keys=True), encoding="utf-8")
    return finalized


def read_fixture(path: Path | str) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))
